# Generated by Django 5.2.1 on 2025-05-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
    ]
